{% set name = "trame-iframe" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trame-iframe-{{ version }}.tar.gz
  sha256: 308901f989832ebb6b3f12c210a55bce5b7fe9dd1e11040b780e341478ef9707

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame_iframe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/trame-iframe
  summary: Helper for iframe/cross-origin communication for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - psavery
